---
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/initializers/*.rb
Rails:
  Enabled: true


Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 140


Metrics/MethodLength:
 Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Security/YAMLLoad:
  Enabled: false

